# Adding and splitting sectors

This notebook shows how to add or split sectors to the packaged IOT test table using an Excel add-sector workbook.

In [1]:
import mario

mario.set_log_verbosity("critical")

In [2]:
db = mario.load_test("IOT")
db.get_index("Sector")

['Agriculture', 'Services', 'Industry']

## Generate an empty add-sector template

In [3]:
db.get_add_sectors_excel(
    # path="add_sector_template.xlsx",
    path = '/Users/lorenzorinaldi/Documents/GitHub/MARIO/mario/test/supporting_files/add_sector_iot_template.xlsx',
    overwrite=True,
)

Read back the Excel file with "Master" sheet filled and get the inventories sheets

In [4]:
db.read_add_sectors_excel(
    path = '/Users/lorenzorinaldi/Documents/GitHub/MARIO/mario/test/supporting_files/add_sector_iot_master_filled.xlsx',
    get_inventories=True,
)

Read back the template with inventories sheets filled

In [5]:
db.read_add_sectors_excel(
    path = '/Users/lorenzorinaldi/Documents/GitHub/MARIO/mario/test/supporting_files/add_sector_iot_inventories_filled.xlsx',
    read_inventories=True,
)

db.inventories.keys()

dict_keys(['New industry', 'New services'])

## Apply a filled add-sector workbook

In [6]:
expanded_db = db.add_sectors(inplace=False)
expanded_db.get_index("Sector")

['Agriculture', 'Industry', 'New industry', 'New services', 'Services']

In [7]:
expanded_db.Z

Region                              Reg1                             \
Level                             Sector
Item                         Agriculture      Industry New industry
Region Level  Item
Reg1   Sector Agriculture   9.308777e+05  5.357865e+06          0.0
              Industry      1.122412e+06  2.289312e+07          0.0
              New industry  0.000000e+00  0.000000e+00          0.0
              New services  0.000000e+00  0.000000e+00          0.0
              Services      1.893611e+06  9.737629e+06          0.0
Reg2   Sector Agriculture   4.168644e+02  2.596073e+03          0.0
              Industry      6.891080e+03  1.335210e+05          0.0
              New industry  0.000000e+00  0.000000e+00          0.0
              New services  0.000000e+00  0.000000e+00          0.0
              Services      1.590111e+03  1.555065e+04          0.0

Region                                                         Reg2  \
Level                                                        Sector
Item                       New services      Services   Agriculture
Region Level  Item
Reg1   Sector Agriculture     15.435331  1.075287e+06   2363.627381
              Industry       183.469920  1.065104e+07   1414.054877
              New industry     0.000000  0.000000e+00      0.000000
              New services     0.000000  0.000000e+00      0.000000
              Services       439.223947  3.059810e+07   1302.054530
Reg2   Sector Agriculture      0.012101  8.430140e+02   2963.307248
              Industry       525.000000  6.555883e+04   9739.395361
              New industry     0.000000  0.000000e+00      0.000000
              New services     0.000000  0.000000e+00      0.000000
              Services         0.551754  3.843739e+04  16684.555239

Region                                                               \
Level
Item                             Industry New industry New services
Region Level  Item
Reg1   Sector Agriculture    50638.344971          0.0          0.0
              Industry      134992.066256          0.0          0.0
              New industry       0.000000          0.0          0.0
              New services       0.000000          0.0          0.0
              Services       27830.640844          0.0          0.0
Reg2   Sector Agriculture    30653.531705          0.0          0.0
              Industry      287474.038293          0.0          0.0
              New industry       0.000000          0.0          0.0
              New services       0.000000          0.0          0.0
              Services      312544.259102          0.0          0.0

Region
Level
Item                             Services
Region Level  Item
Reg1   Sector Agriculture    10343.097378
              Industry       30370.678292
              New industry       0.000000
              New services       0.000000
              Services       58532.069101
Reg2   Sector Agriculture     7962.553289
              Industry      161145.344747
              New industry       0.000000
              New services       0.000000
              Services      722171.520941

In [8]:
expanded_db.Y

Region                                     Reg1                 Reg2
Level                      Consumption category Consumption category
Item                               Final demand         Final demand
Region Level  Item
Reg1   Sector Agriculture          2.533459e+06         1.145534e+04
              Industry             1.816087e+07         1.217507e+05
              New industry         0.000000e+00         0.000000e+00
              New services         1.500000e+03         0.000000e+00
              Services             6.212571e+07         5.286975e+04
Reg2   Sector Agriculture          5.077805e+03         2.935670e+04
              Industry             2.316510e+05         2.998989e+05
              New industry         0.000000e+00         0.000000e+00
              New services         0.000000e+00         0.000000e+00
              Services             5.695455e+04         1.255005e+06